### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by mkrd** [mkrd/Swift-BigInt#14]
The swift package manager makes it a lot easier to manage third party libraries. This library should also support the new package manager

**Comment by twodayslate** [comment]
I don't use the Swift package manager but can't you close this ticket now?

**Comment by mkrd** [comment]
I think in the long term, the native swift package manager will be the most important one, and thus it is reasonable to support it. I will leave this issue open until I or somebody else finds the time to integrate it

**Comment by twodayslate** [comment]
Okay. Based on the README I assumed it was already supported.

**Comment by CraigOpie** [comment]
When trying to use the native Swift Package Manager I get the following: 
error: package has unsupported layout; found loose source files.  

I get this using both branches "master" and "v2.0".  I have Swift 4.2 installed.

**Comment by twodayslate** [comment]
@CraigOpie you might be interested in the following PR https://github.com/mkrd/Swift-Big-Integer/pull/37

**Comment by twodayslate** [comment]
This has been implemented for the base package. Tests haven't been added as some tests requires Tools/

**Comment by twodayslate** [comment]
See https://swiftpackageregistry.com/mkrd/Swift-BigInt
