### ISSUE TITLE
[Question] How to serialize BInt & BDouble

### ISSUE THREAD

**Issue by yuzushioh** [mkrd/Swift-BigInt#26]
I am just wondering how I should serialize `BInt` and `BDouble` to Data type. Is there any good way you can think of?

BigInt has a method for this. (https://github.com/attaswift/BigInt/blob/f2a3c28ce44a8e8ed9cc576d779861d4145bae0e/sources/Data%20Conversion.swift#L81)

**Comment by twodayslate** [comment]
Related #13?

**Comment by mkrd** [comment]
Definitely related. On the first look, NSKeyedArchiver should work, but I'll have to test that in detail

**Comment by twodayslate** [comment]
This was resolved in #50
