### ISSUE TITLE
Refactor readme

### ISSUE THREAD

**Issue by mkrd** [mkrd/Swift-BigInt#31]
Let's face it, the readme could be a lot better. It should be refactored to conform to current conventions, provide a more complete overview of the library and to increase readability

**Comment by twodayslate** [comment]
Alternatively / in addition you could make use of the GitHub wiki feature

**Comment by twodayslate** [comment]
@mkrd  can you enable docs as mentioned in #38?

**Comment by twodayslate** [comment]
Docs: http://mkrd.github.io/Swift-BigInt/

@mkrd if you could put this in the Website section for the project?

Then I think this can be closed after a `./generate-docs.sh`

**Comment by twodayslate** [comment]
I can't for the life of me to get jazzy to work after getting a new mac. I think moving to swiftdoc (and the associated GitHub Action) is the best way forward.
