### ISSUE TITLE
Cleanup master branch for SPM

### ISSUE THREAD

**Issue by mura-admin** [mkrd/Swift-BigInt#36]
It is currently throwing an error that it is not a valid directory structure.

**Comment by mura-admin** [comment]
Swift 4.2

**Comment by twodayslate** [comment]
Related #14

**Comment by mura-admin** [comment]
Created a pull request https://github.com/mkrd/Swift-Big-Integer/pull/37

**Comment by twodayslate** [comment]
Closing since SPM is supported. Directory cleanup should happen but a newer ticket should be created since the main goal of this ticket has been complete.
