### ISSUE TITLE
Update Package.swift to Swift 5 toolchain

### ISSUE THREAD

**Issue by Exey** [mkrd/Swift-BigInt#42]
Trying to add master branch as dependency in Xcode 11 GM 2. Got error: 
`: package at 'https://github.com/mkrd/Swift-BigInt' @ 0b353aa84f2a4c0de499f496ce8d551f07bd8d9c is using Swift tools version 3.1.0 which is no longer supported; consider using '// swift-tools-version:5.1' to specify the current tools version`

**Comment by twodayslate** [comment]
This should be complete.
