### ISSUE TITLE
Valid (n % p) leads to Fatal error: Double value cannot be converted to Int because it is either infinite or NaN

### ISSUE THREAD

**Issue by nolliekrey** [mkrd/Swift-BigInt#45]
4216953730099865132 % 2 will crash (see full details below)
2214286210472843133 % 2 will crash

I'm implementing the Rabin-Miller primality test so I'm generating lots of big ints with BIntMath `randomBInt(...)` and testing to see if they are prime.  I am not using the BIntMath `func isPrime(_ n: BInt) -> Bool`, but rather testing with my implementation of the primality test.

From the console:

Fatal error: Double value cannot be converted to Int because it is either infinite or NaN
2019-12-10 10:21:47.948907-0500 Primes[49528:3931759] Fatal error: Double value cannot be converted to Int because it is either infinite or NaN
(lldb) po n
▿ 4216953730099865132
  - sign : false
  ▿ limbs : 2 elements
    - 0 : 4216953730099865132
    - 1 : 0

(lldb) po n % 2
Fatal error: Double value cannot be converted to Int because it is either infinite or NaN
2019-12-10 10:22:20.063759-0500 Primes[49528:3931759] Fatal error: Double value cannot be converted to Int because it is either infinite or NaN
error: Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0).
The process has been returned to the state before expression evaluation.

BUT check this out. When I try to test I get a BInt with one less limb ... not sure what it means but it seems important.
```

(lldb) po BInt("4216953730099865132")! % 2
▿ 0
  - sign : false
  ▿ limbs : 1 element
    - 0 : 0

```

The randomly created numbers seem different from their string-created siblings.

**Comment by twodayslate** [comment]
`n` is a `BInt`? How was it created?

**Comment by nolliekrey** [comment]
Hello!

Your guess is exactly write.
Yes, `n` is a `BInt`. It was created like so ...
```
            while (r > 0) {
                // choose a random value between l and u
                var rando = BIntMath.randomBInt(bits: l.size)
                while rando < l {
                    // keep trying until it's in the range
                    rando = BIntMath.randomBInt(bits: l.size)
                }
//                let str = "\(rando)"
//                let cleansedRando = BInt(str, radix: 10)!
                if rabinMiller(rando) {
                    print("Found prime: \(rando)")
                    return rando
                }
                r -= 0
            }
```

BUT, when I uncomment the cleanse lines like this I do not crash

```
            while (r > 0) {
                // choose a random value between l and u
                var rando = BIntMath.randomBInt(bits: l.size)
                while rando < l {
                    // keep trying until it's in the range
                    rando = BIntMath.randomBInt(bits: l.size)
                }
                let str = "\(rando)"
                let cleansedRando = BInt(str, radix: 10)!
                if rabinMiller(cleansedRando) {
                    print("Found prime: \(cleansedRando)")
                    return cleansedRando
                }
                r -= 0
            }
```
Note that I'm doing ` let str = "\(rando)"` on purpose because using the constructor that takes a radix also crashes.

**Comment by mkrd** [comment]
I'm looking into it too, but can't reproduce the issue so far. Can you provide a code snippet that replicates the error?

**Comment by nolliekrey** [comment]
Sure! Sorry for the delay.

```
    public static func reproduceNModPError() {
        var r = 1_000_000
        while r > 0 {
            var bitWidth = Int.random(in: 100...256)
            var rando = BIntMath.randomBInt(bits: bitWidth)
            let foo = rando % 2
            r -= 0
        }
    }
```

**Comment by mkrd** [comment]
Alright, I think I got it!
So the function BIntMath.randomBInt generates an invalid BInt (with a leading 0 limb, which is illegal by the definition of limb. This. causes the modulo function to crash, because it assumes that there will never be a leading 0 limb. 
So the core logic is correct, but BIntMath.randomBInt makes the following error:
If a random BInt with `64*n + x` bits is generated, where `x < 64`, there will be a leading limb that is 0 with a probability of `1/(2^x)`. Those limbs should not be appended, but they are, so the error occurs.
