### ISSUE TITLE
Initialization of negative scientific notation

### ISSUE THREAD

**Issue by hugoct** [mkrd/Swift-BigInt#63]
I'm trying to init a BDouble with `BDouble("8.585213060425812e-06")` and `BDouble(8.585213060425812e-06)`.
I'm setting the precision to 32.
Initialising with `String` or `Double` seems to be the same result when call `decimalDescription`:
`8585213.06042581200000000000000000000000`

I think the correct number is supposed to be: `0.00000858521306042581200000000000`

Thanks in advance.

**Comment by twodayslate** [comment]
Let me know if you are still having this issue with the latest commit
