### ISSUE TITLE
Convert hex string to decimal returns null

### ISSUE THREAD

**Issue by k2evil** [mkrd/Swift-BigInt#67]
```
let w = BInt("0b1310c5a2c30000", radix: 16)
```

```
(lldb) po w
nil
```
The problem seems to be with the hex strings starting with `0b`.
`BInt("0b", radix: 16).asString(radix: 10)` also returns zero.

**Comment by twodayslate** [comment]
I bet it's thinking it's binary

https://github.com/mkrd/Swift-BigInt/blob/master/Sources/Swift-Big-Number-Core.swift#L335

**Comment by k2evil** [comment]
> I bet it's thinking it's binary
> 
> https://github.com/mkrd/Swift-BigInt/blob/master/Sources/Swift-Big-Number-Core.swift#L335
Thanks
Do you consider this as a bug or it's just a normal behavior?

**Comment by k2evil** [comment]
> I bet it's thinking it's binary
> 
> https://github.com/mkrd/Swift-BigInt/blob/master/Sources/Swift-Big-Number-Core.swift#L335

Thanks for the response.
Do you consider it as a bug or it's just a normal behavior?

**Comment by twodayslate** [comment]
Yeah this looks like a bug.
