### ISSUE TITLE
Publish v2.2.1

### ISSUE THREAD

**Issue by mkrd** [mkrd/Swift-BigInt#75]
@twodayslate lets publish a new release, since a few fixed have been merged recently. 
Since I didn't setup the package manager stuff, I'm not sure how to do it.
Can you maybe tell me how it is done?
Is it as simple as making a new Github release, or is it more involved, like uploading to a package registry?

**Comment by twodayslate** [comment]
For CocoaPods you'll have to have to update the version number and push to trunk. https://guides.cocoapods.org/making/making-a-cocoapod.html

For SPM you just create a new release on GitHub.

**Comment by ypopovych** [comment]
Hi!

Please push the latest version to the CocoaPods trunk.

You can set up GitHub Actions to publish it automatically on the GitHub Release event. Here is the config for one of our repositories https://github.com/tesseract-one/Tuples.swift/blob/main/.github/workflows/deploy.yml

In this article you can find how to obtain token for CocoaPods trunk: https://fuller.li/posts/automated-cocoapods-releases-with-ci/

**Comment by mkrd** [comment]
I get the error `[!] {"name"=>["is not present"]}` when trying to obtain the token. To be honest, it's been so long that I don't remember if I even published to cocoapods before, or maybe it was @twodayslate. I would need to have some kind of cocoapods account to be able to get that token, right?

**Comment by ypopovych** [comment]
try to register from scratch `pod trunk register your@email 'Your Name' --description='CI session'`

**Comment by ypopovych** [comment]
I think someone used the name BigNumber on CocoaPods already: https://cocoapods.org/pods/BigNumber

In my PR I will update the name of the CocoaPod (framework name in Swift will be left to BigNumber) but for the CocoaPod name I think `Swift-BigInt` will be ok (repo name)
